version: "3"
services:
  php:
    image: surenkid/docker-zf2:latest
    container_name: zf2-webserver
    ports:
      - "80:80"
    links:
      - "mysql"
      - "postgres"
      - "solr"
    volumes:
      - ~/docker_data/wwwroot:/zf2-app

  mysql:
    image: mysql:5.7.16
    container_name: zf2-mysql
    ports:
      - "3306:3306"
    volumes:
      - ~/docker_data/mysql/mydata:/var/lib/mysql
      - ~/docker_data/mysql/my.cnf:/etc/mysql/my.conf
      - ~/docker_data/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.conf
    environment:
      MYSQL_ROOT_PASSWORD: "surenkid"

  postgres:
    image: postgres:9.0.22
    container_name: zf2-postgres
    ports:
      - "5432:5432"
    volumes:
      - ~/docker_data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"

  solr:
    image: solr:5.5.4
    container_name: zf2-solr
    ports:
      - "8983:8983"
    volumes:
      - ~/docker_data/solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
 
#volumes:
#  db-data: