version: "3"
services:
  php:
    image: surenkid/docker-zf2:latest
    ports:
      - "80:80"
    depends_on:
      - "mysql"
      - "postgres"
      - "solr"
    volumes:
      - ~/docker_data/wwwroot:/zf2-app

  mysql:
    image: mysql:5.7.16
    ports:
      - "3306:3306"
    volumes:
      - ~/docker_data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "surenkid"

  postgres:
    image: postgres:9.0.22
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"

  solr:
    image: solr:5.5.4
    ports:
      - "8983:8983"
    volumes:
      - ~/docker_data/solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
 
volumes:
  db-data: