version: "3"
services:
  php:
    image: surenkid/docker-zf2:latest
    container_name: zf2-webserver
    ports:
      - "80:80"
    networks:
      - dockerinnernet
    depends_on:
      - "mysql"
      - "postgres"
      - "solr"
    volumes:
      - ~/docker_data/wwwroot:/zf2-app

  mysql:
    image: mysql:5.7.16
    container_name: zf2-mysql
    ports:
      - "3306:3306"
    networks: 
      - dockerinnernet
    volumes:
      - mydata:/var/lib/mysql
      - ~/docker_data/dbdump:/root
    environment:
      MYSQL_ROOT_PASSWORD: "surenkid"

  postgres:
    image: postgres:9.0.22
    container_name: zf2-postgres
    ports:
      - "5432:5432"
    networks: 
      - dockerinnernet
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ~/docker_data/dbdump:/root
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"

  solr:
    image: solr:5.5.4
    container_name: zf2-solr
    ports:
      - "8983:8983"
    networks: 
      - dockerinnernet
    volumes:
      - ~/docker_data/solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore

networks: 
  dockerinnernet:
volumes:
  pgdata:
  mydata: