version: "3"
services:
  nginx:
    image: nginx:1.12-alpine
    container_name: tp3-nginx
    ports:
      - "80:80"
    networks:
      - dockerinnernet
    depends_on:
      - "php"
    volumes:
      - ~/Projects/tp3_project/nginx:/etc/nginx/conf.d
      - ~/Projects/tp3_project/wwwroot:/var/www/html:ro

  php:
    image: surenkid/php53:latest
    container_name: tp3-php
    ports:
      - "9000:9000"
    networks:
      - dockerinnernet
    depends_on:
      - "mysql"
      - "redis"
    volumes:
      - ~/Projects/tp3_project/wwwroot:/var/www/html

  mysql:
    image: mysql:5.6.36
    container_name: tp3-mysql
    ports:
      - "3306:3306"
    networks: 
      - dockerinnernet
    volumes:
      - mydata:/var/lib/mysql
      - ~/Projects/tp3_project/dbdump:/root
    environment:
      MYSQL_ROOT_PASSWORD: "surenkid"

  redis:
    image: redis:3.0-alpine
    container_name: tp3-redis
    ports:
      - "6379:6379"
    networks: 
      - dockerinnernet
    volumes:
      - ~/Projects/tp3_project/redis:/data

networks: 
  dockerinnernet:
volumes:
  mydata: