version: "3"
services:
  nginx:
    image: nginx:1.12-alpine
    container_name: tp3-nginx
    ports:
      - "80:80"
    networks:
      - dockerinnernet
    depends_on:
      - "php"
    volumes:
      - ~/docker_data2/nginx:/etc/nginx/conf.d
      - ~/docker_data2/wwwroot:/var/www/html:ro

  php:
    image: surenkid/php53:latest
    container_name: tp3-php
    ports:
      - "9000:9000"
    networks:
      - dockerinnernet
    depends_on:
      - "mysql"
    volumes:
      - ~/docker_data2/wwwroot:/var/www/html

  mysql:
    image: mysql:5.7.16
    container_name: tp3-mysql
    ports:
      - "3306:3306"
    networks: 
      - dockerinnernet
    volumes:
      - mydata:/var/lib/mysql
      - ~/docker_data2/dbdump:/root
    environment:
      MYSQL_ROOT_PASSWORD: "surenkid"

networks: 
  dockerinnernet:
volumes:
  mydata: